server:
  port: 8007

spring:
  application:
    name: market-service
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 674ea0ed-9be0-4c8b-88d9-1305aa71e336
        group: DEFAULT_GROUP
  datasource:
    url: jdbc:mysql://localhost:3306/power_trading_market?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: power_trading
    password: power_trading123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: redis123

logging:
  level:
    com.power.trading: DEBUG
